In [1]:
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn import datasets, svm

In [4]:
digits = datasets.load_digits()
X = digits.data
Y = digits.target

In [7]:
svc = svm.SVC()
C_s = np.logspace(-10, 0,10)

scores = list()
scores_std = list()


In [8]:
for C in C_s:
    svc.C = C
    this_scores = cross_val_score(svc, X, Y, n_jobs=1)
    scores.append(this_scores)
    scores_std.append(np.std(this_scores))


In [9]:
scores

[array([ 0.1013289 ,  0.10183639,  0.12919463]),
 array([ 0.1013289 ,  0.10183639,  0.12919463]),
 array([ 0.1013289 ,  0.10183639,  0.12919463]),
 array([ 0.1013289 ,  0.10183639,  0.12919463]),
 array([ 0.1013289 ,  0.10183639,  0.12919463]),
 array([ 0.1013289 ,  0.10183639,  0.12919463]),
 array([ 0.1013289 ,  0.10183639,  0.12919463]),
 array([ 0.1013289 ,  0.10183639,  0.12919463]),
 array([ 0.1013289 ,  0.10183639,  0.12919463]),
 array([ 0.39368771,  0.41068447,  0.45973154])]